# Esta línea es crucial para que Render interprete correctamente el archivo.
version: "1"

services:
  # Define el servicio web que se desplegará.
  - name: futbol-api
    type: web
    plan: free # Usa el plan gratuito para evitar cargos.
    env: image # Indica a Render que use una imagen de Docker pre-construida.
    # Desactiva el auto-despliegue de Render, ya que lo controlaremos con el Deploy Hook desde GitHub Actions.
    autoDeploy: false
    image:
      url: ghcr.io/unq-dapp-grupom/futbol-api:main # URL de la imagen en GitHub Container Registry
    healthCheckPath: /actuator/health # Ruta para que Render sepa si tu app está lista.
    # Las variables de entorno se gestionarán directamente en el Dashboard de Render.
    # Esto evita problemas de validación con los secretos en el blueprint.
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production # Activa el perfil de producción de Spring.