# render.yaml
# Documentación: https://render.com/docs/blueprint-spec

services:
  # Un servicio web para la API de fútbol
  - type: web
    name: futbol-api
    # Entorno de ejecución: Imagen Docker pre-construida
    env: image
    # Especifica el plan gratuito para evitar cargos y la necesidad de una tarjeta de crédito.
    plan: free
    # URL de la imagen en GitHub Container Registry
    # Reemplaza 'TU_USUARIO_DE_GITHUB/futbol-api' con tu usuario y nombre de repo
    image:
      url: ghcr.io/unq-dapp-grupom/futbol-api:main
    # Credenciales para acceder al registro de imágenes de GitHub (ghcr.io)
    # Esto le dice a Render que use la cuenta de GitHub conectada para obtener la imagen.
    registryCredential:
      name: github # El nombre de la credencial para ghcr.io
      repository: unq-dapp-grupom/futbol-api # Tu repositorio
    # Configuración de salud para que Render sepa si tu app está lista
    healthCheckPath: /actuator/health # Asegúrate de tener Spring Boot Actuator
    # Variables de entorno (si las necesitas)
    envVars:
      - key: SERVER_PORT
        value: 8080 # Render espera que el servicio escuche en el puerto 8080 por defecto
