# render.yaml
# Documentación: https://render.com/docs/blueprint-spec

services:
  # Un servicio web para la API de fútbol
  - type: web
    name: futbol-api
    # Entorno de ejecución: Imagen Docker pre-construida
    env: image
    # URL de la imagen en GitHub Container Registry
    # Reemplaza 'TU_USUARIO_DE_GITHUB/futbol-api' con tu usuario y nombre de repo
    image:
      url: ghcr.io/TU_USUARIO_DE_GITHUB/futbol-api:main
    # Configuración de salud para que Render sepa si tu app está lista
    healthCheckPath: /actuator/health # Asegúrate de tener Spring Boot Actuator
    # Variables de entorno (si las necesitas)
    envVars:
      - key: SERVER_PORT
        value: 8080 # Render espera que el servicio escuche en el puerto 8080 por defecto
