# render.yaml
# Documentación: https://render.com/docs/blueprint-spec

registries:
  # Define una credencial para acceder a GitHub Container Registry (ghcr.io)
  - name: github-cr # Un nombre para esta credencial
    url: ghcr.io
    github: true # Indica a Render que use la cuenta de GitHub conectada

services:
  # Un servicio web para la API de fútbol
  - type: web
    name: futbol-api
    # Entorno de ejecución: Imagen Docker pre-construida
    env: image
    # Especifica el plan gratuito para evitar cargos y la necesidad de una tarjeta de crédito.
    plan: free
    # URL de la imagen en GitHub Container Registry
    # Reemplaza 'TU_USUARIO_DE_GITHUB/futbol-api' con tu usuario y nombre de repo
    image:
      url: ghcr.io/unq-dapp-grupom/futbol-api:main
    registryCredential:
      name: github-cr # Referencia a la credencial definida arriba
    # Configuración de salud para que Render sepa si tu app está lista
    healthCheckPath: /actuator/health # Asegúrate de tener Spring Boot Actuator
    # Variables de entorno (si las necesitas)
    envVars:
      - key: SERVER_PORT
        value: 8080 # Render espera que el servicio escuche en el puerto 8080 por defecto
