version: "1"

services:
  - name: futbol-api
    type: web
    # Indica a Render que use la instancia gratuita (free plan)
    plan: free 
    image: 
      url: ghcr.io/unq-dapp-grupom/futbol-api:main

    healthCheckPath: /actuator/health # Ruta para que Render sepa si tu app está lista.
    
    # Se recomienda dejar autodeploy: true si quieres CD
    autoDeploy: true 
    
    envVars:
      - key: API_KEY
        fromSecret: true
      
      - key: SPRING_PROFILES_ACTIVE
        value: production