# render.yaml
# Documentación: https://render.com/docs/blueprint-spec
version: "1"

registries:
  # Define una credencial para acceder a GitHub Container Registry (ghcr.io)
  - name: github-cr # Un nombre para esta credencial
    url: ghcr.io
    github: true # Indica a Render que use la cuenta de GitHub conectada

services:
  - name: futbol-api # Un servicio web para la API de fútbol
    type: web
    env: image # Entorno de ejecución: Imagen Docker pre-construida
    plan: free # Especifica el plan gratuito para evitar cargos
    repo: https://github.com/unq-dapp-grupoM/futbol-api # El repositorio de origen
    healthCheckPath: /actuator/health # Ruta para que Render sepa si tu app está lista
    image:
      url: ghcr.io/unq-dapp-grupom/futbol-api:main # URL de la imagen en GitHub Container Registry
    registryCredential:
      name: github-cr # Referencia a la credencial definida en la sección 'registries'
    envVars: # Variables de entorno
      - key: SERVER_PORT
        value: 10000 # Render asigna el puerto dinámicamente, pero es buena práctica definirlo.
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: API_KEY # Ejemplo de variable de entorno secreta
        fromSecret: true # El valor se tomará de los Secretos de Render
