# Esta línea es crucial para que Render interprete correctamente el archivo.
version: "1"

services:
  # Define el servicio web que se desplegará.
  - name: futbol-api
    type: web
    plan: free # Usa el plan gratuito para evitar cargos.
    env: image # Indica a Render que use una imagen de Docker pre-construida.
    autoDeploy: false # Desactiva el auto-despliegue, lo controlamos con el Deploy Hook.
    image:
      url: ghcr.io/unq-dapp-grupom/futbol-api:main # URL de la imagen en GitHub Container Registry
    healthCheckPath: /actuator/health # Ruta para que Render sepa si tu app está lista.
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production # Activa el perfil de producción de Spring.
      # Inyecta los secretos como variables de entorno en Render.
      # Debes crear estas variables en el dashboard de Render para tu servicio.
      - key: API_SECURITY_JWT_SECRET_KEY
        fromSecret: true
      - key: API_SECURITY_KEY
        fromSecret: true