version: "1"

services:
  - name: futbol-api
    type: web
    plan: free
    
    # Configuraci칩n para la imagen Docker preconstruida en GHCR
    image:
      url: ghcr.io/unq-dapp-grupom/futbol-api:main 

    startCommand: "java -jar app.jar" 

    # Render asume que tu aplicaci칩n est치 lista cuando esta ruta responde 200 OK.
    healthCheckPath: /actuator/health 
    
    # Permite que Render se re-despliegue autom치ticamente con cada nuevo commit que 
    # tu GitHub Action suba a GHCR.
    autoDeploy: true

    envVars:
      # Referencia correcta al Secreto de Render (asumiendo que 'API_KEY' existe en tu Dashboard)
      - key: API_KEY
        value: ${{ secret.API_SECURITY_KEY }}

      - key: SPRING_PROFILES_ACTIVE
        value: production